# Generated by Django 4.1.5 on 2023-01-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
