# Generated by Django 4.1.5 on 2023-02-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fia", "0003_remove_userprofile_birth_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_type", models.CharField(max_length=8, unique=True)),
                ("purchase_date", models.DateField()),
                ("stock_price", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Rankings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=8, unique=True)),
                ("net_profit", models.IntegerField()),
                ("net_loss", models.IntegerField()),
            ],
        ),
    ]
