# Generated by Django 4.1.5 on 2023-02-16 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fia", "0004_portfolio_rankings"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="stock_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
