# Generated by Django 4.1.5 on 2023-02-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fia", "0006_rename_stock_type_portfolio_stock_symbol_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="stock_price",
            field=models.FloatField(default=0),
        ),
    ]
