# Generated by Django 4.1.5 on 2023-04-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fia", "0012_forumquestion_forumresponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumquestion",
            name="answered",
            field=models.BooleanField(default=False),
        ),
    ]
