# Generated by Django 4.1.5 on 2023-05-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fia", "0013_forumquestion_answered"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="account_value",
            field=models.FloatField(default=10000.0),
        ),
        migrations.AlterField(
            model_name="accountoverview",
            name="account_value",
            field=models.FloatField(default=10000.0),
        ),
    ]
